PYTHON_WORKER_ERROR = "PYTHON_WORKER_ERROR"
INVALID_INPUT = "INVALID_INPUT"
DOWNLOAD_EXPERIMENT = 'DOWNLOAD_EXPERIMENT'
LOAD_EXPERIMENT = 'LOAD_TO_MEMORY'
STARTED_TASK = 'STARTED_TASK'
COMPRESSING_TASK_DATA = 'COMPRESSING_DATA'
UPLOADING_TASK_DATA = 'UPLOADING_DATA'
FINISHED_TASK = 'FINISHED_TASK'