error_codes <- list(
  GENE_NOT_FOUND = "R_WORKER_GENE_NOT_FOUND",
  EMPTY_CELL_SET = "R_WORKER_EMPTY_CELL_SET",
  COLUMN_NOT_FOUND = "R_WORKER_COLUMN_NOT_FOUND",
  NO_MARKER_GENES = "R_WORKER_NO_MARKER_GENES",
  EMPTY_ROOT_NODES = "R_WORKER_TRAJECTORY_ANALYSIS_EMPTY_ROOT_NODES",
  UNHANDLED_ERROR = "R_WORKER_UNHANDLED_ERROR"
)

ULTIMATE_SEED <- 42

usethis::use_data(error_codes, ULTIMATE_SEED, internal = TRUE, overwrite = TRUE)
