{
  "R": {
    "Version": "4.0.5",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Bioconductor": {
    "Version": "3.12"
  },
  "Packages": {
    "AnnotationDbi": {
      "Package": "AnnotationDbi",
      "Version": "1.52.0",
      "Source": "Bioconductor",
      "Hash": "ca5106b296b3aa6af713ce197be547c1"
    },
    "BH": {
      "Package": "BH",
      "Version": "1.75.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e4c04affc2cac20c8fec18385cd14691"
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.50.0",
      "Source": "Bioconductor",
      "Hash": "f49586e579b712b7e55253aba0c9bc21"
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.36.1",
      "Source": "Bioconductor",
      "Hash": "f628c51eadc74ffd838b801cd22d589a"
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "87a690190741d0791c9c10b390c933ff"
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.24.1",
      "Source": "Bioconductor",
      "Hash": "338a72852f019b3b51ae87dc82391eb3"
    },
    "DBI": {
      "Package": "DBI",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "030aaec5bc6553f35347cbb1e70b1a17"
    },
    "DESeq2": {
      "Package": "DESeq2",
      "Version": "1.30.1",
      "Source": "Bioconductor",
      "Hash": "1e2b51957aa16c8129786e82cb28a708"
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.16.3",
      "Source": "Bioconductor",
      "Hash": "a87d32010153cba996c97fe2a52403e6"
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b56998fff55e4a4b4860ad6e8c67e0f9"
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.26.7",
      "Source": "Bioconductor",
      "Hash": "b8b4dfceea20ddae8893aa4ccb242dea"
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.4",
      "Source": "Bioconductor",
      "Hash": "8e9c39ceac5f1d98d3267541853fca31"
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.42.0",
      "Source": "Bioconductor",
      "Hash": "2826edf1a5ff7d6ce991ec5ed918ec5f"
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.24.1",
      "Source": "Bioconductor",
      "Hash": "21b3bc3dfb55cb9501c5f3413b35388c"
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8dcfa99b14c296bc9f1fd64d52fd3ce7"
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-54",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0e59129db205112e3963904db67fd0dc"
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.3-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ed05e9c9726267e4a5872e09c04587c"
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.2.1",
      "Source": "Bioconductor",
      "Hash": "fbae799fc848a8599a46a3adfe8a975a"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b203113193e70978a696b2809525649d"
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7"
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e031418365a7f7a766181ab5a41a5716"
    },
    "RCurl": {
      "Package": "RCurl",
      "Version": "1.98-1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ddac9abbfba243f9aeab9b5680b968d3"
    },
    "RJSONIO": {
      "Package": "RJSONIO",
      "Version": "1.3-1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5465553c5320701393a2daaa42ed58f9"
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cc151930e20e16427bc3d0daec62b4a9"
    },
    "RSQLite": {
      "Package": "RSQLite",
      "Version": "2.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "71f19d00a7736b24492fb26b483bc450"
    },
    "RSpectra": {
      "Package": "RSpectra",
      "Version": "0.16-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a41329d24d5a98eaed2bd0159adb1b5f"
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dab19adae4440ae55aa8a9d238b246bb"
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4c61a26f751659e875f46045df6d5fad"
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.10.5.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b1c9574190c1c84417eedaa5901138bf"
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.3.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ddfa72a87fdf4c80466a20818be91d00"
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5"
    },
    "RestRserve": {
      "Package": "RestRserve",
      "Version": "0.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3c1eea04870ff3bc9e9100bc2fff67ba"
    },
    "Rserve": {
      "Package": "Rserve",
      "Version": "1.7-3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d70a8c2c56f502a187fe1641b9b1f29b"
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f153432c4ca15b937ccfaa40f167c892"
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.28.1",
      "Source": "Bioconductor",
      "Hash": "f558c55a285751bd72af11d2bb853521"
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "4.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3d0c6a33f32d1433ed728b49bd3f41c5"
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "4.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e5959242d66cfe4de9116fdcec327f80"
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Hash": "2da24c5f66521d18cff602d324834b20"
    },
    "XML": {
      "Package": "XML",
      "Version": "3.99-0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "59b7d0a3d18303ae30ba1246e77faa83"
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.30.0",
      "Source": "Bioconductor",
      "Hash": "9bd9f991fb4ecde6adeff2fa2e401cc5"
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862"
    },
    "annotate": {
      "Package": "annotate",
      "Version": "1.68.0",
      "Source": "Bioconductor",
      "Hash": "3553333f7949ea3d722760136f3660ae"
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e8a22846fff485f0be3770c2da758713"
    },
    "backports": {
      "Package": "backports",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "644043219fc24e190c2f620c1a380a69"
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "543776ae6848fde2f48ff3816d0628bc"
    },
    "bit": {
      "Package": "bit",
      "Version": "4.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f36715f14d94678eea9933af927bc15d"
    },
    "bit64": {
      "Package": "bit64",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9fe98599ca456d6552421db0d6772d8f"
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d8d8ee39869c18d8846a184dd8a1af"
    },
    "blob": {
      "Package": "blob",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9addc7e2c5954eca5719928131fed98c"
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2f01e16ff9571fe70381c7b9ae560dc4"
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2f069f3f42847231aef7baa49bed97b0"
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "34d90fa5845004236b9eacafc51d07b2"
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5346f76a33eb7417812c270b04a5581b"
    },
    "callr": {
      "Package": "callr",
      "Version": "3.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "461aa75a11ce2400245190ef5d3995df"
    },
    "checkmate": {
      "Package": "checkmate",
      "Version": "2.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a667800d5f0350371bedeb8b8b950289"
    },
    "cli": {
      "Package": "cli",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a94ba44cee3ea571e813721e64184172"
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ce49bfe5bc0b3ecd43a01fe1b01c2243"
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "019388fc48e48b3da0d3a76ff94608a8"
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6cab523af06ac301e7a40c5529d45882"
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f22be39ec1d141fd03683c06f3a6e67"
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b418e8423699d11c7f2087c2bfd07da2"
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "730eebcc741a5c36761f7d4d0f5e37b8"
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e75525c55c70e5f4f78c9960a4b402e9"
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2b06f9e415a62b6762e4b8098d2aecbc"
    },
    "curl": {
      "Package": "curl",
      "Version": "4.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c5e68405893f030f139f6d6675eac675"
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d1b8b1a821ee564a3515fa6c6d5c52dc"
    },
    "deldir": {
      "Package": "deldir",
      "Version": "0.2-10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6ba6a411bdd4c1b297bd54e2c5c98385"
    },
    "desc": {
      "Package": "desc",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b6963166f7f10b970af1006c462ce6cd"
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "feb5b7455eba422a2c110bb89852e6a3"
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a0cbe758a531d054b537d16dff4d58a1"
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "19e84500b64bc7e589cb1e2550e25832"
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3ce2af5ead3b01c518fd453c7fe5a51a"
    },
    "ellipsis": {
      "Package": "ellipsis",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb0eec2fe32e88d9e2836c2f73ea2077"
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ec8ca05cffcc70569eaaad8469d2a3a7"
    },
    "fansi": {
      "Package": "fansi",
      "Version": "0.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d447b40982c576a72b779f0a3b3da227"
    },
    "farver": {
      "Package": "farver",
      "Version": "2.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c98eb5133d9cb9e1622b8691487f11bb"
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77bd60a6157420d4ffa93b27cf6a58b8"
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "df82a154b37aad59c6a9cc2b54614296"
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2590a6a868515a69f258640a51b724c9"
    },
    "fs": {
      "Package": "fs",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "44594a07a42e5f91fac9f93fda6d0109"
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e"
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b"
    },
    "future": {
      "Package": "future",
      "Version": "1.21.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f25fad6bee82b7ab01f055e2d813b96f"
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7fb0dc1961807da107ab2078366052bd"
    },
    "genefilter": {
      "Package": "genefilter",
      "Version": "1.72.1",
      "Source": "Bioconductor",
      "Hash": "c25bd3bb0821c2e7cda02b177b20136b"
    },
    "geneplotter": {
      "Package": "geneplotter",
      "Version": "1.68.0",
      "Source": "Bioconductor",
      "Hash": "beb82d45bc852daee31a515bf818d561"
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4d243a9c10b00589889fe32314ffd902"
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3eb6477d01eb5bbdc03f7d5f70f2733e"
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "08ab869f37e6a7741a64ab9069bcb67d"
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9d028e8f37c84dba356ce3c367a1978e"
    },
    "globals": {
      "Package": "globals",
      "Version": "0.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "eca8023ed5ca6372479ebb9b3207f5ae"
    },
    "glue": {
      "Package": "glue",
      "Version": "1.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6efd734b14c6471cfe443345f3e35e29"
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3c9209bce1b10900155ea37ce954cf30"
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e65e5d5dea4cbb9ba822dcd782b2ee1f"
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7d7f283939f563670a697165b2cf5560"
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ac5c6baf7822ce8732b343f14c072c4d"
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.9.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2ace6c4a06297d0b364e0444384a2b82"
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "af2c2531e55df5cf230c4b5444fc973c"
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6fdaa86d0700f8b3e92ee3c445a5a10d"
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "54344a78aae37bc6ef39b1240969df8e"
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a525aba14184fec243f9eaec62fbed43"
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ba9b882bb834ecbdad37338a11f3f8"
    },
    "igraph": {
      "Package": "igraph",
      "Version": "1.2.6.9118",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "rigraph",
      "RemoteUsername": "igraph",
      "RemoteRef": "master",
      "RemoteSha": "46bfafd9623b4c9d6cbad9b6768ba3fb297fc06b",
      "Hash": "d0bc05b3feb0bb04b8f6aae3d4d14271"
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a9ad517358000d57022401ef18ee657a"
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b2008df40fb297e3fef135c7e8eeec1a"
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5aab57a3bd297eee1c1d862735972182"
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "98138e0994d41508c7a6b84a0600cfcb"
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3d5108641f47470611a32d0bdf357a72"
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad"
    },
    "later": {
      "Package": "later",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b61890ae77fea19fc8acadd25db70aa4"
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.20-44",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f36bf1a849d9106dc2af72e501f9de41"
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370"
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "355993b12fa6e5c9e4b1f9077adabfbd"
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3471fb65971f1a7b2d4ae7848cf2db8d"
    },
    "limma": {
      "Package": "limma",
      "Version": "3.46.0",
      "Source": "Bioconductor",
      "Hash": "78b860aa595c42e02464243a213b3e6d"
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.8.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0bde42ee282efb18c7c4e63822f5b4f7"
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-38",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b0edacc02f7a3dad41a1afc385e929f4"
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "760b5b542e8435237d1b3c253bfe18e7"
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "41287f1ac7d28a92f0a286ed507928d3"
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "0.59.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "45a2fee40a2f1bcad392cbe8a5f10d4f"
    },
    "memoise": {
      "Package": "memoise",
      "Version": "2.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a0bc51650201a56d00a4798523cc91b3"
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.8-36",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "93cc747b0e1ad882a4570463c3575c23"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "26fa77e707223e1ce042b2b5d09993dc"
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fec5f52652d60615fdb3957b3d74324a"
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6dfe8bf774944bd5595785e3229d8771"
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-152",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "35de1ce639f20b5e10f7f46260730c65"
    },
    "openssl": {
      "Package": "openssl",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f4dbc5a47fd93d3415249884d31d6791"
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.26.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "08925887608f7086dd7522933ff43a93"
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c446b30cb33ec125ff02588b60660ccb"
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "52f8028b028076bc3b7ee5d6251abf0d"
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8672ae02bd20f6479bce2d06c7ff1401"
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "01f28d4278f15c76cddbea05899c5d6f"
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "463642747f81879e6752485aefb831cf"
    },
    "plogr": {
      "Package": "plogr",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "09eb987710984fc2905c7129c7d85e65"
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.9.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3f385f2cd5c270ea3bbe68cb94f7c558"
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ec0e5ab4e5f851f6ef32cd1d1984957f"
    },
    "png": {
      "Package": "png",
      "Version": "0.1-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "03b7076c234cb3331288919983326c55"
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cb167f328b3ada4ec5cf67a7df4c900a"
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f"
    },
    "presto": {
      "Package": "presto",
      "Version": "1.0.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "immunogenomics",
      "RemoteRepo": "presto",
      "RemoteRef": "master",
      "RemoteSha": "052085db9c88aa70a28d11cc58ebc807999bf0ad",
      "Hash": "bf01a4a8947398ef32d019e8d8282222"
    },
    "processx": {
      "Package": "processx",
      "Version": "3.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0cbca2bc4d16525d009c4dbba156b37c"
    },
    "promises": {
      "Package": "promises",
      "Version": "1.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ab2c43adb4d4699cf3690acd378d75d"
    },
    "ps": {
      "Package": "ps",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "32620e2001c1dce1af49c49dccbb9420"
    },
    "purrr": {
      "Package": "purrr",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "97def703420c8ab10d8f0e6c72101e02"
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d"
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "76c9e04c712a05848ae7a23d2f170a40"
    },
    "renv": {
      "Package": "renv",
      "Version": "0.13.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "079cb1f03ff972b30401ed05623cbe92"
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb5996d0bd962d214a11140d77589917"
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "30ab0ea8c8d3dd16a3fa06903449bbfb"
    },
    "rlang": {
      "Package": "rlang",
      "Version": "0.4.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "515f341d3affe0de9e4a7f762efb0456"
    },
    "rpart": {
      "Package": "rpart",
      "Version": "4.1-15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9787c1fcb680e655d062e7611cadf78e"
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "249d8cd1e74a8f6a26194a91b47f21d1"
    },
    "rstudioapi": {
      "Package": "rstudioapi",
      "Version": "0.13",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "06c85365a03fdaf699966cc1d3cf53ea"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "50cf822feb64bb3977bda0b7091be623"
    },
    "scales": {
      "Package": "scales",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6f76f71042411426ec8df6c54f34e6dd"
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "373eb417aadd7c7f35861953f3fe3deb"
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f6423b883393222fb5c022799374ccec"
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6e3b6ae7fe02b5859e4bb277f218b8ae"
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f9ba299f2385e686745b066c6d7a7c4"
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "11b822ad6214111a4188d5e5fd1b144c"
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "947e4e02a79effa5d512473e10f41797"
    },
    "spatstat.core": {
      "Package": "spatstat.core",
      "Version": "2.1-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6c1e3cc9e7df1bdfd312e4e75339feae"
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4e8002e034d7d0af852b2bbcce851c2e"
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a0a2cda8121279a62604dd24b5a4b9d4"
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "2.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "615efff0d33e612b15dc3fc3ba0cc554"
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "72200a58cae0d7046e416e6be6d9d322"
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9df5e6f9a7fa11b84adf0429961de66a"
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0759e6b6c0957edb1311028a49a35e76"
    },
    "survival": {
      "Package": "survival",
      "Version": "3.2-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f4d706b25d640dbaeb56d9c9b6ce9a22"
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b227d13e29222b4574486cfcbde077fa"
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090"
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "495e0434d9305716b6a87031570ce109"
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "349b40a9f144516d537c875e786ec8b8"
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "450d7dfaedde58e28586b854eeece4fa"
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7243004a708d06d4716717fa1ff5b2fe"
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c3ad47dc6da0751f18ed53c4613e3ac7"
    },
    "uuid": {
      "Package": "uuid",
      "Version": "0.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e4169eb989a5d03ccb6b628cad1b1b50"
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.1.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a9737c75f5f949695617b05e78281b2f"
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ecf749a1b39ea72bd9b51b76292261f1"
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "55e157e2aa88161bdb0754218470d204"
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.2.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "20c45f1d511a3f730b7b469f4d11e104"
    },
    "withr": {
      "Package": "withr",
      "Version": "2.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ad03909b44677f930fa156d47d7a3aeb"
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2"
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2826c5d9efb0a88f657c7a679c7106db"
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.36.0",
      "Source": "Bioconductor",
      "Hash": "effcbe90f6986ca6f81ce4d67db7238b"
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "035d1c7c12593038c26fb1c2fd40c4d2"
    }
  }
}
