{
  "R": {
    "Version": "4.4.0",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.19/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.19/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.19/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.19/workflows"
      },
      {
        "Name": "BioCbooks",
        "URL": "https://bioconductor.org/packages/3.19/books"
      },
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      },
      {
        "Name": "CRAN-Snapshot",
        "URL": "https://packagemanager.rstudio.com/cran/2023-03-31"
      }
    ]
  },
  "Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.84.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a8235afbcd6316e6e91433ea47661013"
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.64.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "utils"
      ],
      "Hash": "9bc4cabd3bfda461409172213d932813"
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ef32d07aafdd12f24c5827374ae3590d"
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "47e968dfe563c1b22c2e20a067ec21d5"
    },
    "BiocNeighbors": {
      "Package": "BiocNeighbors",
      "Version": "1.22.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "RcppHNSW",
        "S4Vectors",
        "methods",
        "stats"
      ],
      "Hash": "da9f332c88453734623406dcca13ee03"
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "R",
        "codetools",
        "cpp11",
        "futile.logger",
        "methods",
        "parallel",
        "snow",
        "stats",
        "utils"
      ],
      "Hash": "7b6e79f86e3d1c23f62c5e2052e848d4"
    },
    "BiocSingular": {
      "Package": "BiocSingular",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "ScaledMatrix",
        "beachmat",
        "irlba",
        "methods",
        "rsvd",
        "utils"
      ],
      "Hash": "9d2e9fbd803f4eddfeb307b1ee376aad"
    },
    "BiocVersion": {
      "Package": "BiocVersion",
      "Version": "3.19.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "b892e27fc9659a4c8f8787d34c37b8b2"
    },
    "Cairo": {
      "Package": "Cairo",
      "Version": "1.5-15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "c13c98ad29dc1aa5f22f80a9199c4627"
    },
    "DBI": {
      "Package": "DBI",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "164809cd72e1d5160b4cb3aa57f510fe"
    },
    "DESeq2": {
      "Package": "DESeq2",
      "Version": "1.44.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "BiocParallel",
        "GenomicRanges",
        "IRanges",
        "MatrixGenerics",
        "Rcpp",
        "RcppArmadillo",
        "S4Vectors",
        "SummarizedExperiment",
        "ggplot2",
        "locfit",
        "matrixStats",
        "methods",
        "stats4"
      ],
      "Hash": "a90e0e67215ba95ccb29e93b169caaa4"
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.30.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "SparseArray",
        "methods",
        "stats",
        "stats4"
      ],
      "Hash": "395472c65cd9d606a1a345687102f299"
    },
    "DelayedMatrixStats": {
      "Package": "DelayedMatrixStats",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors",
        "methods",
        "sparseMatrixStats"
      ],
      "Hash": "5d9536664ccddb0eaa68a90afe4ee76e"
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "b56998fff55e4a4b4860ad6e8c67e0f9"
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.40.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDbData",
        "IRanges",
        "R",
        "S4Vectors",
        "UCSC.utils",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "614124bc9fb80d222cfa0d2e3e76c339"
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.12",
      "Source": "Bioconductor",
      "Requirements": [
        "R"
      ],
      "Hash": "c3c792a7b7f2677be56e8632c5b7543d"
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.56.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "0fab423e3f49e207681eb404d9182a1e"
    },
    "HDF5Array": {
      "Package": "HDF5Array",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "IRanges",
        "Matrix",
        "R",
        "Rhdf5lib",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "rhdf5",
        "rhdf5filters",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "b10ddb24baf506cf7b4bc868ae65b984"
    },
    "HGNChelper": {
      "Package": "HGNChelper",
      "Version": "0.8.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "d756e596f0f9ddd90b82921f5964b71b"
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "S4Vectors",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "836770692f7c8401090519228b93af32"
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-20",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "8dcfa99b14c296bc9f1fd64d52fd3ce7"
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-60",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "a56a6365b3fa73293ea8d084be0d9bb0"
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.6-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "8c7115cd3a0e048bda2a7cd110549f7a"
    },
    "Matrix.utils": {
      "Package": "Matrix.utils",
      "Version": "0.9.8",
      "Source": "URL",
      "Repository": "CRAN",
      "RemoteType": "url",
      "RemoteUrl": "https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.8.tar.gz",
      "Requirements": [
        "Matrix",
        "R",
        "grr",
        "methods",
        "stats"
      ],
      "Hash": "837bf62ea47730acce356702fb99c47e"
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "matrixStats",
        "methods"
      ],
      "Hash": "152dbbcde6a9a7c7f3beef79b68cd76a"
    },
    "R.methodsS3": {
      "Package": "R.methodsS3",
      "Version": "1.8.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "278c286fd6e9e75d0c2e8f731ea445c8"
    },
    "R.oo": {
      "Package": "R.oo",
      "Version": "1.25.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "methods",
        "utils"
      ],
      "Hash": "a0900a114f4f0194cf4aa8cd4a700681"
    },
    "R.utils": {
      "Package": "R.utils",
      "Version": "2.12.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "R.oo",
        "methods",
        "tools",
        "utils"
      ],
      "Hash": "3dc2829b790254bfba21e60965787651"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "470851b6d5d0ac559e9d01bb352b4021"
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7"
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "45f0398006e83a5b10b72a90663d8d8c"
    },
    "RJSONIO": {
      "Package": "RJSONIO",
      "Version": "1.3-1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods"
      ],
      "Hash": "0c7658433758cea5bcae50edd02b55b7"
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "gplots",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "cc151930e20e16427bc3d0daec62b4a9"
    },
    "RSpectra": {
      "Package": "RSpectra",
      "Version": "0.16-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen"
      ],
      "Hash": "6b5ab997fd5ff6d46a5f1d9f8b76961c"
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "utils"
      ],
      "Hash": "5ea2700d21e038ace58269ecdbeb9ec0"
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods"
      ],
      "Hash": "4c61a26f751659e875f46045df6d5fad"
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.12.8.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "1eb4a0603478b5557b77d75534251371"
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.4.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "stats",
        "utils"
      ],
      "Hash": "df49e3306f232ec28f1604e36a202847"
    },
    "RcppHNSW": {
      "Package": "RcppHNSW",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "methods"
      ],
      "Hash": "1f2dc32c27746a35196aaf95adb357be"
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5"
    },
    "RcppTOML": {
      "Package": "RcppTOML",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "f8a578aa91321ecec1292f1e2ffadeda"
    },
    "ResidualMatrix": {
      "Package": "ResidualMatrix",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "26b5d104b2d27d7aa3725c4e3aa1b3b9"
    },
    "RestRserve": {
      "Package": "RestRserve",
      "Version": "0.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "Rcpp",
        "Rserve",
        "checkmate",
        "jsonlite",
        "methods",
        "mime",
        "parallel",
        "uuid"
      ],
      "Hash": "3c1eea04870ff3bc9e9100bc2fff67ba"
    },
    "Rhdf5lib": {
      "Package": "Rhdf5lib",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "c92ba8b9a2c5c9ff600a1062a3b7b727"
    },
    "RhpcBLASctl": {
      "Package": "RhpcBLASctl",
      "Version": "0.21-247.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e0d1744b1339290bce02b1699230b8b5"
    },
    "Rserve": {
      "Package": "Rserve",
      "Version": "1.7-3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d70a8c2c56f502a187fe1641b9b1f29b"
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "stats"
      ],
      "Hash": "f81f7764a3c3e310b1d40e1a8acee19e"
    },
    "S4Arrays": {
      "Package": "S4Arrays",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "R",
        "S4Vectors",
        "abind",
        "crayon",
        "methods",
        "stats"
      ],
      "Hash": "665d1f150ce8a6e7614375eafdbad645"
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.42.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "245ac721ca6088200392ea5251db9e3c"
    },
    "ScaledMatrix": {
      "Package": "ScaledMatrix",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "bac1c808a92d9c3f45d05e7a8c1b74f0"
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "4.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "MASS",
        "Matrix",
        "R",
        "RANN",
        "RColorBrewer",
        "ROCR",
        "Rcpp",
        "RcppAnnoy",
        "RcppEigen",
        "RcppProgress",
        "Rtsne",
        "SeuratObject",
        "cluster",
        "cowplot",
        "fitdistrplus",
        "future",
        "future.apply",
        "ggplot2",
        "ggrepel",
        "ggridges",
        "grDevices",
        "graphics",
        "grid",
        "httr",
        "ica",
        "igraph",
        "irlba",
        "jsonlite",
        "leiden",
        "lmtest",
        "matrixStats",
        "methods",
        "miniUI",
        "patchwork",
        "pbapply",
        "plotly",
        "png",
        "reticulate",
        "rlang",
        "scales",
        "scattermore",
        "sctransform",
        "shiny",
        "spatstat.core",
        "spatstat.geom",
        "stats",
        "tibble",
        "tools",
        "utils",
        "uwot"
      ],
      "Hash": "0d7350ea71e070760974a50692596c4d"
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "5.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen",
        "future",
        "future.apply",
        "generics",
        "grDevices",
        "grid",
        "lifecycle",
        "methods",
        "progressr",
        "rlang",
        "sp",
        "spam",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "e9b70412b7e04571b46101f5dcbaacad"
    },
    "SeuratWrappers": {
      "Package": "SeuratWrappers",
      "Version": "0.3.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "satijalab",
      "RemoteRepo": "seurat-wrappers",
      "RemoteRef": "master",
      "RemoteSha": "9652bddba522d2f00ec5f8f0f8227761b9a6afd2",
      "Remotes": "welch-lab/liger, hms-dbmi/conos, immunogenomics/harmony, immunogenomics/presto, satijalab/seurat-data, velocyto-team/velocyto.R, SaskiaFreytag/schex@031320d, cole-trapnell-lab/monocle3, mojaveazure/seurat-disk, powellgenomicslab/Nebulosa, atakanekiz/CIPR-Package, prabhakarlab/Banksy",
      "Requirements": [
        "BiocManager",
        "Matrix",
        "R",
        "Seurat",
        "cowplot",
        "ggplot2",
        "igraph",
        "methods",
        "remotes",
        "rlang",
        "rsvd",
        "stats",
        "utils"
      ],
      "Hash": "a33261877a1ad80ca3282ea2f7beaa9e"
    },
    "SingleCellExperiment": {
      "Package": "SingleCellExperiment",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "GenomicRanges",
        "S4Vectors",
        "SummarizedExperiment",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "4476ad434a5e7887884521417cab3764"
    },
    "SparseArray": {
      "Package": "SparseArray",
      "Version": "1.4.3",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "XVector",
        "matrixStats",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "97e01fd020665f2b0c6bd182b0ab68c2"
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.34.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "2f6c8cc972ed6aee07c96e3dff729d15"
    },
    "UCSC.utils": {
      "Package": "UCSC.utils",
      "Version": "1.0.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "S4Vectors",
        "httr",
        "jsonlite",
        "methods",
        "stats"
      ],
      "Hash": "83d45b690bffd09d1980c224ef329f5b"
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.44.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "R",
        "S4Vectors",
        "methods",
        "tools",
        "utils",
        "zlibbioc"
      ],
      "Hash": "4245b9938ac74c0dbddbebbec6036ab4"
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862"
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "cad6cf7f1d5f6e906700b9d3e718c796"
    },
    "assertthat": {
      "Package": "assertthat",
      "Version": "0.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tools"
      ],
      "Hash": "50c838a310445e954bc13f26f26a6ecf"
    },
    "backports": {
      "Package": "backports",
      "Version": "1.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c39fbec8a30d23e721980b8afb31984c"
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "543776ae6848fde2f48ff3816d0628bc"
    },
    "batchelor": {
      "Package": "batchelor",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "ResidualMatrix",
        "S4Vectors",
        "ScaledMatrix",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "igraph",
        "methods",
        "scuttle",
        "stats",
        "utils"
      ],
      "Hash": "ec5dcf85cdf644b078d02deaf27a3bfd"
    },
    "beachmat": {
      "Package": "beachmat",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "SparseArray",
        "methods"
      ],
      "Hash": "10e94b1bce9070632a40c6b873f8b2d4"
    },
    "beeswarm": {
      "Package": "beeswarm",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "0f4e9d8caa6feaa7e409ae6c30f2ca66"
    },
    "bit": {
      "Package": "bit",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d242abec29412ce988848d0294b208fd"
    },
    "bit64": {
      "Package": "bit64",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bit",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "9fe98599ca456d6552421db0d6772d8f"
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d8d8ee39869c18d8846a184dd8a1af"
    },
    "boot": {
      "Package": "boot",
      "Version": "1.3-28",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "0baa960e3b49c6176a4f42addcbacc59"
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "68bd2b066e1fe780bbf62fc8bcc36de3"
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "magrittr",
        "rlang",
        "sass"
      ],
      "Hash": "2f069f3f42847231aef7baa49bed97b0"
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bitops"
      ],
      "Hash": "34d90fa5845004236b9eacafc51d07b2"
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.0.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "fastmap",
        "rlang"
      ],
      "Hash": "c35768291560ce302c0a6589f92e837d"
    },
    "callr": {
      "Package": "callr",
      "Version": "3.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "processx",
        "utils"
      ],
      "Hash": "d7e13f49c19103ece9e58ad2d83a7354"
    },
    "checkmate": {
      "Package": "checkmate",
      "Version": "2.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "backports",
        "utils"
      ],
      "Hash": "c01cab1cb0f9125211a6fc99d540e315"
    },
    "class": {
      "Package": "class",
      "Version": "7.3-22",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "stats",
        "utils"
      ],
      "Hash": "f91f6b29f38b8c280f2b9477787d4bb2"
    },
    "classInt": {
      "Package": "classInt",
      "Version": "0.4-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "R",
        "class",
        "e1071",
        "grDevices",
        "graphics",
        "stats"
      ],
      "Hash": "9c04a89713e4c4f9c0f3bf9ef928f852"
    },
    "cli": {
      "Package": "cli",
      "Version": "3.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "1216ac65ac55ec0058a6f75d7ca0fd52"
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "ce49bfe5bc0b3ecd43a01fe1b01c2243"
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c089a619a7fae175d149d89164f8c7d8"
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "f20c47fd52fae58b4e377c37bb8c335b"
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f22be39ec1d141fd03683c06f3a6e67"
    },
    "covr": {
      "Package": "covr",
      "Version": "3.6.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "crayon",
        "digest",
        "httr",
        "jsonlite",
        "methods",
        "rex",
        "stats",
        "utils",
        "withr",
        "yaml"
      ],
      "Hash": "0cbf0435830e767ba9b292b313592362"
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grDevices",
        "grid",
        "gtable",
        "methods",
        "rlang",
        "scales"
      ],
      "Hash": "b418e8423699d11c7f2087c2bfd07da2"
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5a295d7d963cc5035284dcdbaf334f4e"
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "methods",
        "utils"
      ],
      "Hash": "e8a1e41acf02548751f45c718d55aa6a"
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "htmltools",
        "jsonlite",
        "lazyeval"
      ],
      "Hash": "2b06f9e415a62b6762e4b8098d2aecbc"
    },
    "curl": {
      "Package": "curl",
      "Version": "5.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "411ca2c03b1ce5f548345d2fc2685f7a"
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.15.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "8ee9ac56ef633d0c7cab8b2ca87d683e"
    },
    "deldir": {
      "Package": "deldir",
      "Version": "2.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "24754fce82729ff85317dd195b6646a8"
    },
    "desc": {
      "Package": "desc",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "utils"
      ],
      "Hash": "99b79fcbd6c4d1ce087f5c5c758b384f"
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "crayon",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "bcaa8b95f8d7d01a5dedfd959ce88ab8"
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.35",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "698ece7ba5a4fa4559e3d537e7ec3d31"
    },
    "dotCall64": {
      "Package": "dotCall64",
      "Version": "1.1-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "80f374ef8500fcdc5d84a0345b837227"
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "ellipsis",
        "generics",
        "glue",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "rlang",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "19e84500b64bc7e589cb1e2550e25832"
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "BH",
        "R",
        "Rcpp",
        "sitmo"
      ],
      "Hash": "3ce2af5ead3b01c518fd453c7fe5a51a"
    },
    "e1071": {
      "Package": "e1071",
      "Version": "1.7-14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "class",
        "grDevices",
        "graphics",
        "methods",
        "proxy",
        "stats",
        "utils"
      ],
      "Hash": "4ef372b716824753719a8a38b258442d"
    },
    "edgeR": {
      "Package": "edgeR",
      "Version": "4.2.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rcpp",
        "graphics",
        "limma",
        "locfit",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "20783ecb7e7cea3f351e8b21153e3eb8"
    },
    "ellipsis": {
      "Package": "ellipsis",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "rlang"
      ],
      "Hash": "bb0eec2fe32e88d9e2836c2f73ea2077"
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "daf4a1246be12c1fa8c7705a0935c1a0"
    },
    "fansi": {
      "Package": "fansi",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "utils"
      ],
      "Hash": "962174cf2aeb5b9eea581522286a911f"
    },
    "farver": {
      "Package": "farver",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "680887028577f3fa2a81e410ed0d6e42"
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f7736a18de97dea803bde0a2daaafb27"
    },
    "filelock": {
      "Package": "filelock",
      "Version": "1.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "38ec653c2613bed60052ba3787bd8a2c"
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "grDevices",
        "methods",
        "stats",
        "survival"
      ],
      "Hash": "df82a154b37aad59c6a9cc2b54614296"
    },
    "foreign": {
      "Package": "foreign",
      "Version": "0.8-86",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "550170303dbb19d07b2bcc288068e7dc"
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "63cb26d12517c7863f5abb006c5e0f25"
    },
    "fs": {
      "Package": "fs",
      "Version": "1.6.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15aeb8c27f5ea5161f9f6a641fafd93a"
    },
    "furrr": {
      "Package": "furrr",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "future",
        "globals",
        "lifecycle",
        "purrr",
        "rlang",
        "vctrs"
      ],
      "Hash": "c7cf394610e3aaf086fa4b66c382016e"
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "futile.options",
        "lambda.r",
        "utils"
      ],
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e"
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b"
    },
    "future": {
      "Package": "future",
      "Version": "1.33.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "digest",
        "globals",
        "listenv",
        "parallel",
        "parallelly",
        "utils"
      ],
      "Hash": "fd7b1d69d16d0d114e4fa82db68f184c"
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.11.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "future",
        "globals",
        "parallel",
        "utils"
      ],
      "Hash": "afe1507511629f44572e6c53b9baeb7c"
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15e9634c0fcd294799e9b2e929ed1b86"
    },
    "ggbeeswarm": {
      "Package": "ggbeeswarm",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "beeswarm",
        "ggplot2",
        "vipor"
      ],
      "Hash": "dd68b9b215b2d3119603549a794003c3"
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "cli",
        "glue",
        "grDevices",
        "grid",
        "gtable",
        "isoband",
        "lifecycle",
        "mgcv",
        "rlang",
        "scales",
        "stats",
        "tibble",
        "vctrs",
        "withr"
      ],
      "Hash": "44c6a2f8202d5b7e878ea274b1092426"
    },
    "ggrastr": {
      "Package": "ggrastr",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "Cairo",
        "R",
        "ggbeeswarm",
        "ggplot2",
        "grid",
        "png",
        "ragg"
      ],
      "Hash": "8dabdab0c31adb630b6e0fabfdc0968d"
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "ggplot2",
        "grid",
        "rlang",
        "scales"
      ],
      "Hash": "08ab869f37e6a7741a64ab9069bcb67d"
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grid",
        "plyr",
        "scales",
        "withr"
      ],
      "Hash": "9d028e8f37c84dba356ce3c367a1978e"
    },
    "globals": {
      "Package": "globals",
      "Version": "0.16.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "codetools"
      ],
      "Hash": "2580567908cafd4f187c1e5a91e98b7f"
    },
    "glue": {
      "Package": "glue",
      "Version": "1.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "e0b3a53876554bd45879e596cdb10a52"
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "dbe0201f91eeb15918dd3fbf01ee689a"
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "R",
        "caTools",
        "gtools",
        "stats"
      ],
      "Hash": "e65e5d5dea4cbb9ba822dcd782b2ee1f"
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "utils"
      ],
      "Hash": "7d7f283939f563670a697165b2cf5560"
    },
    "grr": {
      "Package": "grr",
      "Version": "0.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "195f3206842ea5ae11968e8d462bb828"
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "grid",
        "lifecycle",
        "rlang"
      ],
      "Hash": "e18861963cbc65a27736e02b3cd3c4a0"
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.9.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "2ace6c4a06297d0b364e0444384a2b82"
    },
    "here": {
      "Package": "here",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "rprojroot"
      ],
      "Hash": "24b224366f9c2e7534d2344d10d59211"
    },
    "hms": {
      "Package": "hms",
      "Version": "1.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ellipsis",
        "lifecycle",
        "methods",
        "pkgconfig",
        "rlang",
        "vctrs"
      ],
      "Hash": "41100392191e1244b887878b533eea91"
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "base64enc",
        "digest",
        "grDevices",
        "rlang",
        "utils"
      ],
      "Hash": "af2c2531e55df5cf230c4b5444fc973c"
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.5.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "htmltools",
        "jsonlite",
        "yaml"
      ],
      "Hash": "6fdaa86d0700f8b3e92ee3c445a5a10d"
    },
    "httptest": {
      "Package": "httptest",
      "Version": "4.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "curl",
        "digest",
        "httr",
        "jsonlite",
        "stats",
        "testthat",
        "utils"
      ],
      "Hash": "c971c66d9224aa506c9c6abc5a5968c9"
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.6.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "Rcpp",
        "later",
        "promises",
        "utils"
      ],
      "Hash": "d55aa087c47a63ead0f6fc10f8fa1ee0"
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "curl",
        "jsonlite",
        "mime",
        "openssl"
      ],
      "Hash": "ac107251d9d9fd72f0ca8049988f1d7f"
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ba9b882bb834ecbdad37338a11f3f8"
    },
    "igraph": {
      "Package": "igraph",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "cli",
        "cpp11",
        "grDevices",
        "graphics",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgconfig",
        "rlang",
        "stats",
        "utils",
        "vctrs"
      ],
      "Hash": "c3b7d801d722e26e4cd888e042bf9af5"
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "methods",
        "stats"
      ],
      "Hash": "acb06a47b732c6251afd16e19c3201ff"
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grid",
        "utils"
      ],
      "Hash": "0080607b4a1a7b28979aecef976d8bc2"
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools"
      ],
      "Hash": "5aab57a3bd297eee1c1d862735972182"
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.8.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods"
      ],
      "Hash": "e1b9c55281c5adc4dd113652d9e26768"
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "graphics",
        "stats"
      ],
      "Hash": "b64ec208ac5bc1852b285f665d6368b3"
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "formatR"
      ],
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad"
    },
    "later": {
      "Package": "later",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "rlang"
      ],
      "Hash": "a3e051d405326b8b0012377434c62b37"
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.22-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "stats",
        "utils"
      ],
      "Hash": "7c5e89f04e72d6611c77451f6331a091"
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370"
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "igraph",
        "methods",
        "reticulate"
      ],
      "Hash": "355993b12fa6e5c9e4b1f9077adabfbd"
    },
    "leidenbase": {
      "Package": "leidenbase",
      "Version": "0.1.11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "igraph"
      ],
      "Hash": "bd72de3ef45531ade16d35db3385b652"
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "rlang"
      ],
      "Hash": "b8552d117e1b808b09a832f589b79035"
    },
    "limma": {
      "Package": "limma",
      "Version": "3.60.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "statmod",
        "stats",
        "utils"
      ],
      "Hash": "eb9369d11da98acc7f7ca4cdab0ee3d8"
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "e2fca3e12e4db979dccc6e519b10a7ee"
    },
    "lme4": {
      "Package": "lme4",
      "Version": "1.1-35.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen",
        "boot",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "minqa",
        "nlme",
        "nloptr",
        "parallel",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "07fb0c5b727b15b0ce40feb641498e4e"
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-38",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats",
        "zoo"
      ],
      "Hash": "b0edacc02f7a3dad41a1afc385e929f4"
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "lattice"
      ],
      "Hash": "3885127e04b35dafded049075057ad83"
    },
    "lpSolve": {
      "Package": "lpSolve",
      "Version": "5.6.18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "12c7a918599d5700e4265dd8a21f684f"
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "7ce2733a9826b3aeb1775d56fd305472"
    },
    "maketools": {
      "Package": "maketools",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "1621cb95007b3e1626bb5597c5faf799"
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4b3ea27a19d669c0405b38134d89a9d1"
    },
    "memoise": {
      "Package": "memoise",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cachem",
        "rlang"
      ],
      "Hash": "e2817ccf4a065c5d9d7f2cfbe7c1d78c"
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.9-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "nlme",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "110ee9d83b496279960e162ac97764ce"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tools"
      ],
      "Hash": "18e9c28c1d3ca1560ce30658b22ce104"
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "shiny",
        "utils"
      ],
      "Hash": "fec5f52652d60615fdb3957b3d74324a"
    },
    "minqa": {
      "Package": "minqa",
      "Version": "1.2.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp"
      ],
      "Hash": "f48238f8d4740426ca12f53f27d004dd"
    },
    "mockery": {
      "Package": "mockery",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "testthat"
      ],
      "Hash": "c28ce5f7c2293d76b91657f3fe30c50b"
    },
    "monocle3": {
      "Package": "monocle3",
      "Version": "1.2.9",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "cole-trapnell-lab",
      "RemoteRepo": "monocle3",
      "RemoteRef": "master",
      "RemoteSha": "87f6e88760566065179ae5039d524da7d032cc15",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "HDF5Array",
        "MASS",
        "Matrix",
        "Matrix.utils",
        "R",
        "RANN",
        "RColorBrewer",
        "Rcpp",
        "RcppAnnoy",
        "RcppHNSW",
        "RhpcBLASctl",
        "Rtsne",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "assertthat",
        "batchelor",
        "digest",
        "dplyr",
        "future",
        "ggplot2",
        "ggrastr",
        "ggrepel",
        "grr",
        "igraph",
        "irlba",
        "leidenbase",
        "limma",
        "lme4",
        "lmtest",
        "methods",
        "openssl",
        "pbapply",
        "pbmcapply",
        "pheatmap",
        "plotly",
        "plyr",
        "proxy",
        "pscl",
        "purrr",
        "reshape2",
        "rsample",
        "shiny",
        "slam",
        "spdep",
        "speedglm",
        "stats",
        "stringr",
        "terra",
        "tibble",
        "tictoc",
        "tidyr",
        "utils",
        "uwot",
        "viridis"
      ],
      "Hash": "822dcdcfd314f315ead1276b80ed35e3"
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "colorspace",
        "methods"
      ],
      "Hash": "4fd8900853b746af55b81fda99da7695"
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-163",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "8d1938040a05566f4f7a14af4feadd6b"
    },
    "nloptr": {
      "Package": "nloptr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "testthat"
      ],
      "Hash": "277c67a08f358f42b6a77826e4492f79"
    },
    "nnet": {
      "Package": "nnet",
      "Version": "7.3-19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "2c797b46eea7fb58ede195bc0b1f1138"
    },
    "openssl": {
      "Package": "openssl",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "askpass"
      ],
      "Hash": "ea2475b073243d9d338aa8f086ce973e"
    },
    "openxlsx": {
      "Package": "openxlsx",
      "Version": "4.2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "grDevices",
        "methods",
        "stats",
        "stringi",
        "utils",
        "zip"
      ],
      "Hash": "e398ce13682a7409d16e13df09f65875"
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.37.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "parallel",
        "tools",
        "utils"
      ],
      "Hash": "5410df8d22bd36e616f2a2343dbb328c"
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "stats",
        "utils"
      ],
      "Hash": "c446b30cb33ec125ff02588b60660ccb"
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.4-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "parallel"
      ],
      "Hash": "52f8028b028076bc3b7ee5d6251abf0d"
    },
    "pbmcapply": {
      "Package": "pbmcapply",
      "Version": "1.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "parallel",
        "utils"
      ],
      "Hash": "bf173fb42b60f8f404f7a9f9c3f95d0d"
    },
    "pheatmap": {
      "Package": "pheatmap",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "scales",
        "stats"
      ],
      "Hash": "db1fb0021811b6693741325bbe916e58"
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.9.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cli",
        "fansi",
        "glue",
        "lifecycle",
        "rlang",
        "utf8",
        "utils",
        "vctrs"
      ],
      "Hash": "15da5a8412f317beeee6175fbc76f4bb"
    },
    "pkgbuild": {
      "Package": "pkgbuild",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "desc",
        "processx"
      ],
      "Hash": "a29e8e134a460a01e0ca67a4763c595b"
    },
    "pkgcache": {
      "Package": "pkgcache",
      "Version": "2.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "curl",
        "filelock",
        "jsonlite",
        "prettyunits",
        "processx",
        "rappdirs",
        "tools",
        "utils"
      ],
      "Hash": "2622106d5651a653c55430ee5f583978"
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "01f28d4278f15c76cddbea05899c5d6f"
    },
    "pkgdepends": {
      "Package": "pkgdepends",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "curl",
        "desc",
        "filelock",
        "glue",
        "jsonlite",
        "lpSolve",
        "pkgbuild",
        "pkgcache",
        "prettyunits",
        "processx",
        "ps",
        "rprojroot",
        "stats",
        "utils",
        "zip"
      ],
      "Hash": "d0a9c1ca3fbc82d3db84e65f09b42720"
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "crayon",
        "desc",
        "fs",
        "glue",
        "methods",
        "pkgbuild",
        "rlang",
        "rprojroot",
        "utils",
        "withr"
      ],
      "Hash": "876c618df5ae610be84356d5d7a5d124"
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.9.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "base64enc",
        "crosstalk",
        "data.table",
        "digest",
        "dplyr",
        "ggplot2",
        "htmltools",
        "htmlwidgets",
        "httr",
        "jsonlite",
        "lazyeval",
        "magrittr",
        "promises",
        "purrr",
        "rlang",
        "scales",
        "tibble",
        "tidyr",
        "tools",
        "vctrs",
        "viridisLite"
      ],
      "Hash": "3f385f2cd5c270ea3bbe68cb94f7c558"
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "ec0e5ab4e5f851f6ef32cd1d1984957f"
    },
    "png": {
      "Package": "png",
      "Version": "0.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "bd54ba8a0a5faded999a7aab6e46b374"
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "436542aadb70675e361cf359285af7c7"
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f"
    },
    "presto": {
      "Package": "presto",
      "Version": "1.0.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "immunogenomics",
      "RemoteRepo": "presto",
      "RemoteRef": "master",
      "RemoteSha": "052085db9c88aa70a28d11cc58ebc807999bf0ad",
      "Requirements": [
        "DESeq2",
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "data.table",
        "dplyr",
        "methods",
        "reshape2",
        "rlang",
        "stats",
        "tidyr",
        "utils"
      ],
      "Hash": "bf01a4a8947398ef32d019e8d8282222"
    },
    "prettyunits": {
      "Package": "prettyunits",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "6b01fc98b1e86c4f705ce9dcfd2f57c7"
    },
    "processx": {
      "Package": "processx",
      "Version": "3.8.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "ps",
        "utils"
      ],
      "Hash": "0c90a7d71988856bad2a2a45dd871bb9"
    },
    "progress": {
      "Package": "progress",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "crayon",
        "hms",
        "prettyunits"
      ],
      "Hash": "14dc9f7a3c91ebb14ec5bb9208a07061"
    },
    "progressr": {
      "Package": "progressr",
      "Version": "0.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "digest",
        "utils"
      ],
      "Hash": "ac50c4ffa8f6a46580dd4d7813add3c4"
    },
    "promises": {
      "Package": "promises",
      "Version": "1.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "Rcpp",
        "later",
        "magrittr",
        "rlang",
        "stats"
      ],
      "Hash": "4ab2c43adb4d4699cf3690acd378d75d"
    },
    "proxy": {
      "Package": "proxy",
      "Version": "0.4-27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "e0ef355c12942cf7a6b91a6cfaea8b3e"
    },
    "ps": {
      "Package": "ps",
      "Version": "1.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "dd2b9319ee0656c8acf45c7f40c59de7"
    },
    "pscl": {
      "Package": "pscl",
      "Version": "1.5.5",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "MASS",
        "datasets",
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "c55158537b8c4754a8c3de3382f1a659"
    },
    "purrr": {
      "Package": "purrr",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "magrittr",
        "rlang"
      ],
      "Hash": "97def703420c8ab10d8f0e6c72101e02"
    },
    "ragg": {
      "Package": "ragg",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "systemfonts",
        "textshaping"
      ],
      "Hash": "14932bb6f2739c771ca4ceaba6b4248e"
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d"
    },
    "raster": {
      "Package": "raster",
      "Version": "3.5-21",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods",
        "sp",
        "terra"
      ],
      "Hash": "2a312d1edc9253ed38245f586744216e"
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tibble"
      ],
      "Hash": "76c9e04c712a05848ae7a23d2f170a40"
    },
    "remotes": {
      "Package": "remotes",
      "Version": "2.4.2",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "227045be9aee47e6dda9bb38ac870d67"
    },
    "renv": {
      "Package": "renv",
      "Version": "1.0.7",
      "OS_type": null,
      "NeedsCompilation": "no",
      "Repository": "CRAN",
      "Source": "Repository"
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "plyr",
        "stringr"
      ],
      "Hash": "bb5996d0bd962d214a11140d77589917"
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.26-9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "reticulate",
      "RemoteRef": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "RemoteSha": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppTOML",
        "graphics",
        "here",
        "jsonlite",
        "methods",
        "png",
        "rappdirs",
        "utils",
        "withr"
      ],
      "Hash": "1fbd16fb844017519cdede66bc95a5a2"
    },
    "rex": {
      "Package": "rex",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "lazyeval"
      ],
      "Hash": "ae34cd56890607370665bee5bd17812f"
    },
    "rhdf5": {
      "Package": "rhdf5",
      "Version": "2.48.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rhdf5lib",
        "methods",
        "rhdf5filters"
      ],
      "Hash": "74d8c5aeb96d090ce8efc9ffd16afa2b"
    },
    "rhdf5filters": {
      "Package": "rhdf5filters",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rhdf5lib"
      ],
      "Hash": "99e15369f8fb17dc188377234de13fc6"
    },
    "rlang": {
      "Package": "rlang",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "42548638fae05fd9a9b5f3f437fbbbe2"
    },
    "rpart": {
      "Package": "rpart",
      "Version": "4.1.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats"
      ],
      "Hash": "b3d390424f41d04174cccf84d49676c2"
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4c8415e0ec1e29f3f4f6fc108bef0144"
    },
    "rrapply": {
      "Package": "rrapply",
      "Version": "1.2.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "65e732ee965ecaef51b5d71267d5ca74"
    },
    "rsample": {
      "Package": "rsample",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "dplyr",
        "ellipsis",
        "furrr",
        "generics",
        "glue",
        "methods",
        "pillar",
        "purrr",
        "rlang",
        "slider",
        "tibble",
        "tidyr",
        "tidyselect",
        "vctrs"
      ],
      "Hash": "d3ef8543c8f3b44990cc122909847087"
    },
    "rsvd": {
      "Package": "rsvd",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R"
      ],
      "Hash": "b462187d887abc519894874486dbd6fd"
    },
    "s2": {
      "Package": "s2",
      "Version": "1.1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "wk"
      ],
      "Hash": "32f7b1a15bb01ae809022960abad5363"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.4.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "fs",
        "htmltools",
        "rappdirs",
        "rlang"
      ],
      "Hash": "d53dbfddf695303ea4ad66f86e99b95d"
    },
    "scales": {
      "Package": "scales",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "RColorBrewer",
        "cli",
        "farver",
        "glue",
        "labeling",
        "lifecycle",
        "munsell",
        "rlang",
        "viridisLite"
      ],
      "Hash": "c19df082ba346b0ffa6f833e92de34d1"
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "scales"
      ],
      "Hash": "373eb417aadd7c7f35861953f3fe3deb"
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "dplyr",
        "future",
        "future.apply",
        "ggplot2",
        "gridExtra",
        "magrittr",
        "matrixStats",
        "methods",
        "reshape2",
        "rlang"
      ],
      "Hash": "85ff27d18c45a92993f6d7fd09c41f79"
    },
    "scuttle": {
      "Package": "scuttle",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "6d94b72071aefd6e8b041c34ee83ebd0"
    },
    "sf": {
      "Package": "sf",
      "Version": "1.0-16",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "DBI",
        "R",
        "Rcpp",
        "classInt",
        "grDevices",
        "graphics",
        "grid",
        "magrittr",
        "methods",
        "s2",
        "stats",
        "tools",
        "units",
        "utils"
      ],
      "Hash": "ad57b543f7c3fca05213ba78ff63df9b"
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "bslib",
        "cachem",
        "commonmark",
        "crayon",
        "digest",
        "ellipsis",
        "fastmap",
        "glue",
        "grDevices",
        "htmltools",
        "httpuv",
        "jsonlite",
        "later",
        "lifecycle",
        "methods",
        "mime",
        "promises",
        "rlang",
        "sourcetools",
        "tools",
        "utils",
        "withr",
        "xtable"
      ],
      "Hash": "6e3b6ae7fe02b5859e4bb277f218b8ae"
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "0f9ba299f2385e686745b066c6d7a7c4"
    },
    "slam": {
      "Package": "slam",
      "Version": "0.1-50",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "e25793551cbdb843154152e5ee88cbd6"
    },
    "slider": {
      "Package": "slider",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ellipsis",
        "glue",
        "rlang",
        "vctrs",
        "warp"
      ],
      "Hash": "5237bd176dc0c4dd7eb8dcdafe514de3"
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "40b74690debd20c57d93d8c246b305d4"
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "947e4e02a79effa5d512473e10f41797"
    },
    "sp": {
      "Package": "sp",
      "Version": "2.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "75940133cca2e339afce15a586f85b11"
    },
    "spData": {
      "Package": "spData",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "raster",
        "sp"
      ],
      "Hash": "5d68152962bb57448336effdcf598d0a"
    },
    "spam": {
      "Package": "spam",
      "Version": "2.10-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "dotCall64",
        "grid",
        "methods"
      ],
      "Hash": "ffe1f9e95a4375530747b268f82b5086"
    },
    "sparseMatrixStats": {
      "Package": "sparseMatrixStats",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Matrix",
        "MatrixGenerics",
        "Rcpp",
        "matrixStats",
        "methods"
      ],
      "Hash": "7e500a5a527460ca0406473bdcade286"
    },
    "spatial": {
      "Package": "spatial",
      "Version": "7.3-17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "1229a01b4ec059e9f2396724f2ec9010"
    },
    "spatstat.core": {
      "Package": "spatstat.core",
      "Version": "2.4-4",
      "Source": "URL",
      "Repository": "CRAN",
      "RemoteType": "url",
      "RemoteUrl": "https://cran.r-project.org/src/contrib/Archive/spatstat.core/spatstat.core_2.4-4.tar.gz",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "goftest",
        "grDevices",
        "graphics",
        "methods",
        "mgcv",
        "nlme",
        "rpart",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.random",
        "spatstat.sparse",
        "spatstat.utils",
        "stats",
        "tensor",
        "utils"
      ],
      "Hash": "2f7ef6ee31ead12a5ee4996f91051477"
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "spatstat.utils"
      ],
      "Hash": "114a35341cb4955e1b8d30e28ec356c6"
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "3.2-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "deldir",
        "grDevices",
        "graphics",
        "methods",
        "polyclip",
        "spatstat.data",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "96b9f23da42d16660aa6d136ad99cf5f"
    },
    "spatstat.random": {
      "Package": "spatstat.random",
      "Version": "3.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "methods",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "01aff260c49550e820a47d97e566af6a"
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "3.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "methods",
        "spatstat.utils",
        "stats",
        "tensor",
        "utils"
      ],
      "Hash": "1daaecefd754bb259a5ad5ce95a2cdcc"
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "81d929f43f8532c1f8180a105449d414"
    },
    "spdep": {
      "Package": "spdep",
      "Version": "1.2-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "boot",
        "deldir",
        "e1071",
        "grDevices",
        "graphics",
        "methods",
        "s2",
        "sf",
        "sp",
        "spData",
        "stats",
        "units",
        "utils"
      ],
      "Hash": "971a08b9692589feaf487abbd042886c"
    },
    "speedglm": {
      "Package": "speedglm",
      "Version": "0.3-4",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "MASS",
        "Matrix",
        "methods",
        "stats"
      ],
      "Hash": "a82eb1b2d58393b1e548982e467026e5"
    },
    "statmod": {
      "Package": "statmod",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "26e158d12052c279bdd4ba858b80fb1f"
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "bba431031d30789535745a9627ac9271"
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "glue",
        "magrittr",
        "stringi"
      ],
      "Hash": "0759e6b6c0957edb1311028a49a35e76"
    },
    "survival": {
      "Package": "survival",
      "Version": "3.5-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "b8e943d262c3da0b0febd3e04517c197"
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3a1be13d68d47a8cd0bfd74739ca1555"
    },
    "systemfonts": {
      "Package": "systemfonts",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11"
      ],
      "Hash": "90b28393209827327de889f49935140a"
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090"
    },
    "terra": {
      "Package": "terra",
      "Version": "1.7-71",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods"
      ],
      "Hash": "e8611881ab70a4fb7a1f629b31e6fcff"
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.2.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "brio",
        "callr",
        "cli",
        "desc",
        "digest",
        "evaluate",
        "jsonlite",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgload",
        "praise",
        "processx",
        "ps",
        "rlang",
        "utils",
        "waldo",
        "withr"
      ],
      "Hash": "3f6e7e5e2220856ff865e4834766bf2b"
    },
    "textshaping": {
      "Package": "textshaping",
      "Version": "0.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "systemfonts"
      ],
      "Hash": "1ab6223d3670fac7143202cb6a2d43d5"
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "fansi",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "pkgconfig",
        "rlang",
        "utils",
        "vctrs"
      ],
      "Hash": "a84e2cc86d07289b3b6f5069df7a004c"
    },
    "tictoc": {
      "Package": "tictoc",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "5acb66b0266ad1f0ebf7ffe1aa36ff4c"
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "dplyr",
        "ellipsis",
        "glue",
        "lifecycle",
        "magrittr",
        "purrr",
        "rlang",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "450d7dfaedde58e28586b854eeece4fa"
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ellipsis",
        "glue",
        "purrr",
        "rlang",
        "vctrs"
      ],
      "Hash": "7243004a708d06d4716717fa1ff5b2fe"
    },
    "tzdb": {
      "Package": "tzdb",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11"
      ],
      "Hash": "b2e1cbce7c903eaf23ec05c58e59fb5e"
    },
    "units": {
      "Package": "units",
      "Version": "0.8-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "119d19da480e873f72241ff6962ffd83"
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "62b65c52671e6665f803ff02954446e9"
    },
    "uuid": {
      "Package": "uuid",
      "Version": "1.1-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "3d78edfb977a69fc7a0341bee25e163f"
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.1.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "FNN",
        "Matrix",
        "RSpectra",
        "Rcpp",
        "RcppAnnoy",
        "RcppProgress",
        "dqrng",
        "irlba",
        "methods"
      ],
      "Hash": "a9737c75f5f949695617b05e78281b2f"
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "rlang"
      ],
      "Hash": "c03fa420630029418f7e6da3667aac4a"
    },
    "vipor": {
      "Package": "vipor",
      "Version": "0.4.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "ea85683da7f2bfa63a98dc6416892591"
    },
    "viridis": {
      "Package": "viridis",
      "Version": "0.6.2",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R",
        "ggplot2",
        "gridExtra",
        "stats",
        "viridisLite"
      ],
      "Hash": "ee96aee95a7a563e5496f8991e9fde4b"
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c826c7c4241b6fc89ff55aaea3fa7491"
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "diffobj",
        "fansi",
        "glue",
        "methods",
        "rematch2",
        "rlang",
        "tibble"
      ],
      "Hash": "c7d3fd6d29ab077cbac8f0e2751449e6"
    },
    "warp": {
      "Package": "warp",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": "RSPM",
      "Requirements": [
        "R"
      ],
      "Hash": "2982481615756e24e79fee95bdc95daa"
    },
    "withr": {
      "Package": "withr",
      "Version": "3.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "d31b6c62c10dcf11ec530ca6b0dd5d35"
    },
    "wk": {
      "Package": "wk",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5d4545e140e36476f35f20d0ca87963e"
    },
    "xml2": {
      "Package": "xml2",
      "Version": "1.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "methods",
        "rlang"
      ],
      "Hash": "1d0336142f4cd25d8d23cd3ba7a8fb61"
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2"
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "29240487a071f535f5e5d5a323b7afbd"
    },
    "zip": {
      "Package": "zip",
      "Version": "2.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d98c94dacb7e0efcf83b0a133a705504"
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Hash": "3db02e3c460e1c852365df117a2b441b"
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "035d1c7c12593038c26fb1c2fd40c4d2"
    }
  }
}
