name: Create a new release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  create-release:
    name: ${{ format('Create release {0}', github.event.inputs.repo) }}
    runs-on: ubuntu-20.04
    steps:

      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: create-release
        name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}
        
      - id: initialize-git-info
        name: Initialize mandatory git info
        run: git config user.name "Github Actions"
      
      - id: push-release
        name: Push new release branch
        run: git push origin release/${{ github.event.inputs.version }}

      - id: create-pr
        name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
          body: |
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            
            This release candidate should be staged in :
            https://ui-${{ github.event.inputs.version }}.scp-staging.biomage.net/

            Merging this PR will create a GitHub release, update master & develop branches, and upload any assets that are created as part of the release build.